language: node_js
sudo: required
node_js:
  - "6"
  - "7"
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - sleep 15
script:
  - npm test
after_success: 'npm run coveralls'
